### ISSUE TITLE
Закомментированного кода быть не должно

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework1Calculator#2]
https://github.com/HelgaJava/git-homework1Calculator/blob/8698ee439fe3921858c416dbe7447c63fe4fd754/src/Main.java#L15-L16

**Comment by HelgaJava** [comment]
это был один из вариантов округления
// double countLineWallpaperFromOneRoll = lengthRollWallpapepr / (heightRoom + 10/100);
//countLineWallpaperInOneRoll = (int) countLineWallpaperFromOneRoll
но потом я подумала, что округлять надо все-таки в большую сторону в данном случае, поэтому просто преобразование к int не подойдет. А вы что думаете

**Comment by HelgaJava** [comment]
Проверить ДЗ 1 исправления
