### ISSUE TITLE
Может всё-таки int?

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework1Calculator#3]
https://github.com/HelgaJava/git-homework1Calculator/blob/50bffb37f5f3ae399939229d47b5dddc3e646830/src/Main.java#L10-L18

**Comment by HelgaJava** [comment]
а вот здесь у меня как раз-таки и возник самый большой вопрос. С одной стороны значения, которые у нас получатся при вычислении не факт, что будут int. С другой нам по любому надо округлить до целых в большую сторону. Вот я и думаю, то ли явное преобразование сделать, то ли сразу int объявить? Но если сразу int, то дробная часть просто отбросится и все, в таком случае корректен ли в принципе будет результат. Может, я что-то не так понимаю? В общем, здесь нужен совет профи.

**Comment by coursar** [comment]
Приводите к int. Вы же итак округляете через Math.ceil

**Comment by HelgaJava** [comment]
сделано. Сейчас вариант только переоткрыть
