### ISSUE TITLE
Если длина комнаты - то в периметре надо умножать на 2, если длина двух сторон, то должно быть понятно из названия

### ISSUE THREAD

**Issue by coursar** [HelgaJava/git-homework1Calculator#4]
https://github.com/HelgaJava/git-homework1Calculator/blob/50bffb37f5f3ae399939229d47b5dddc3e646830/src/Main.java#L3-L6

**Comment by HelgaJava** [comment]
Да, точно, 2 стороны у комнаты никак не бывает) Исправила
